build_from: "dolibarr/dolibarr:20"
labels:
  org.opencontainers.image.title: "Dolibarr"
  org.opencontainers.image.description: "Dolibarr Server pour Home Assistant"
  org.opencontainers.image.source: "https://github.com/LeGitHubDeTai/ha_addons/dolibarr"
  org.opencontainers.image.licenses: "MIT license"