name: "Draw.io"
version: "26.5.1"
slug: "drawio"
description: "Auto-hébergé Draw.io comme add-on"
startup: services
boot: auto
webui: http://[HOST]:[PORT:1665]/
image: ghcr.io/legithubdetai/ha_addons/dev-drawio-{arch}
ports:
  1665/tcp: 1665
arch:
  - amd64
  - aarch64
