[supervisord]
user=root
nodaemon=true
loglevel=debug
logfile_maxbytes=1000000
logfile_backups=1

[program:nginx]
command=bash /app/nginx-entrypoint.sh
autorestart=true

[program:redis]
command=/usr/bin/redis-server --appendonly yes --maxmemory-policy noeviction --dir /var/lib/redis
user=redis
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:docmost]
command=bash /app/docmost-entrypoint.sh
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
