[supervisord]
user=root
nodaemon=true
loglevel=error
logfile=/dev/null
logfile_maxbytes=0
logfile_backups=0
pidfile=/dev/null

[program:planka]
command=/bin/sh -c "mkdir -p /data/user-avatars /data/project-background-images /data/attachments && chmod +x /scripts/run.sh && exec /scripts/run.sh"
autorestart=unexpected
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=root
stopasgroup=true
killasgroup=true
redirect_stderr=true
priority=100
