[supervisord]
user=root
nodaemon=true
loglevel=error
logfile=/dev/null
logfile_maxbytes=0
logfile_backups=0
pidfile=/dev/null

[program:planka]
command=/bin/sh -c "cd /app && sleep 5 && /run.sh"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=root
environment=NODE_ENV=production,PORT=1338,EXPLICIT_HOST=0.0.0.0
priority=10
startsecs=15

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;" -c /etc/nginx/nginx.conf
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=root
priority=20
startsecs=5
