name: ISOMan
version: "26.3.1.87"
slug: isomandev
panel_title: ISOMan - Linux ISO Manager
panel_icon: "mdi:disc"
description: ISO management tool for downloading and managing ISO images with web interface
url: https://github.com/LeGitHubDeTai/ha_addons/tree/main/isoman
image: ghcr.io/legithubdetai/ha_addons/dev-isomandev-{arch}
arch:
    - amd64
startup: application
boot: auto
hassio_role: "default"
ingress: true
ingress_stream: true
ingress_port: 50145
backup_exclude:
    - "isoman/.cache"
    - "isoman/.logs"
    - "supervisord.log*"
    - "/data/isos/*.tmp"
    - "/share/isos/*.tmp"
map:
    - share:rw
environment:
    PUBLIC_WS_FORCE: "%ws_force%"
ports:
    8080/tcp: null
ports_description:
    8080/tcp: The port for ISOMan web interface. Normally not exposed, as Home Assistant Ingress is more secure and is recommended. You may expose this port if you want to bypass Ingress (not recommended for security reasons).
options:
    ws_force: "auto"   # auto | ws | wss
schema:
    ws_force: list(auto|ws|wss)
