name: ISOMan
version: "26.3.1.18"
slug: isoman
panel_icon: "mdi:disc"
description: ISO management tool for downloading and managing ISO images with web interface
url: https://github.com/aloks98/isoman
webui: http://[HOST]:[PORT:8080]/
image: ghcr.io/legithubdetai/ha_addons/dev-isoman-{arch}
arch:
    - amd64
startup: application
boot: auto
hassio_role: "default"
ingress: true
ingress_port: 8080
ingress_stream: true
backup_exclude:
    - "isoman/.cache"
    - "isoman/.logs"
    - "supervisord.log*"
    - "/data/isos/*.tmp"
map:
    - ssl:ro
    - backup:rw
    - share:rw
    - media:rw
    - config:rw
ports:
    8080/tcp: null
ports_description:
    8080/tcp: The port for ISOMan web interface. Normally not exposed, as Home Assistant Ingress is more secure and is recommended. You may expose this port if you want to bypass the Ingress (not recommended for security reasons).
options:
    env_vars_list: []
schema:
    env_vars_list: [
      "match(^[A-Z_0-9]+: .*$)"
    ]
