[supervisord]
user=root
nodaemon=true
loglevel=info
logfile_maxbytes=1000000
logfile_backups=1

[program:isoman]
command=/bin/sh -c "mkdir -p /share/isoman/isos /share/isoman/db && chown -R isoman:isoman /share/isoman && /entrypoint.sh ./server"
autorestart=unexpected
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
user=root
environment=PORT=8080,DATA_DIR=/share/isoman,WORKER_COUNT=2,DB_MAX_OPEN_CONNS=25,GIN_MODE=release,PUBLIC_WS_FORCE="%{options.ws_force}"

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
user=root
