name: Storybook
version: "26.9.1"
slug: storybook
panel_icon: "mdi:book-open-variant"
description: Component-driven UI development environment — build, document, and test UI components in isolation
url: https://github.com/LeGitHubDeTai/ha_addons/tree/main/storybook
webui: http://[HOST]:[PORT:6006]/
image: ghcr.io/legithubdetai/ha_addons/storybook-{arch}
arch:
    - amd64
    - aarch64
startup: application
boot: auto
hassio_role: "default"
ingress: true
ingress_port: 6006
map:
    - ssl:ro
    - backup:rw
    - share:rw
    - homeassistant_config:rw
ports:
    6006/tcp: null
ports_description:
    6006/tcp: The port for Storybook web interface. Normally not exposed, as Home Assistant Ingress is more secure and is recommended. You may expose this port if you want to bypass Ingress (not recommended for security reasons).
options:
    env_vars_list: []
schema:
    env_vars_list: [
      "match(^[A-Z_0-9]+: .*$)"
    ]
