name: Scanopy
version: "26.3.4.49"
slug: scanopy
panel_title: Scanopy - Network Scanner
panel_icon: "mdi:network"
description: Network scanning tool for discovering and analyzing network devices with web interface
url: https://github.com/LeGitHubDeTai/ha_addons/tree/main/scanopy
image: ghcr.io/legithubdetai/ha_addons/scanopy-{arch}
arch:
    - amd64
startup: application
boot: auto
hassio_role: "default"
ingress: true
ingress_port: 50146
backup_exclude:
    - "scanopy/.cache"
    - "scanopy/.logs"
    - "supervisord.log*"
    - "/data/scans/*.tmp"
    - "/share/scans/*.tmp"
map:
    - share:rw
ports:
    8080/tcp: null
ports_description:
    8080/tcp: The port for Scanopy web interface. Normally not exposed, as Home Assistant Ingress is more secure and is recommended. You may expose this port if you want to bypass Ingress (not recommended for security reasons).
options:
    env_vars_list: []
schema:
    env_vars_list: [
      "match(^[A-Z_0-9]+: .*$)"
    ]
