[supervisord]
user=root
nodaemon=true
loglevel=error
logfile=/dev/null
logfile_maxbytes=0
logfile_backups=0
pidfile=/dev/null

[program:scanopy]
command=/bin/sh -c "mkdir -p /share/scanopy/scans /share/scanopy/db && chown -R scanopy:scanopy /share/scanopy && chmod +x /app/run.sh && exec su-exec scanopy /app/run.sh"
autorestart=unexpected
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=root
environment=SCANOPY_SERVER_PORT=60072,DATA_DIR=/share/scanopy
stopasgroup=true
killasgroup=true
redirect_stderr=true

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user=root
stopasgroup=true
killasgroup=true
redirect_stderr=true
