[supervisord]
user=root
nodaemon=true
loglevel=info
logfile=/dev/stdout
logfile_maxbytes=0
logfile_backups=0

[program:scanopy]
command=/bin/sh -c "mkdir -p /share/scanopy/scans /share/scanopy/db && chown -R scanopy:scanopy /share/scanopy && su-exec scanopy /app/server"
autorestart=unexpected
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
user=root
environment=PORT=60072,DATA_DIR=/share/scanopy
stopasgroup=true
killasgroup=true

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
user=root
stopasgroup=true
killasgroup=true
