worker_processes  1;
error_log /dev/stdout info;
pid /var/run/nginx.pid;

events {
    worker_connections 128;
}

http {
    access_log /dev/stdout;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile on;

    include /etc/nginx/hass-n8n-*.conf;

    client_header_timeout 900s;
    client_body_timeout   900s;
    send_timeout          900s;
    keepalive_timeout     900s;

    proxy_connect_timeout 900s;
    proxy_send_timeout    900s;
    proxy_read_timeout    900s;

    client_max_body_size 0;

    ##
    ## UI n8n (interne via ingress HA)
    ##
    server {
        listen 5690;
        server_name _;

        allow $NGINX_ALLOWED_IP;
        deny all;

        location / {
            proxy_pass http://localhost:5678;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_cache off;
            proxy_buffering off;
        }
    }

    ##
    ## Webhooks / API (exposés)
    ##
    server {
        listen 8081;
        server_name _;

        ## ===== CORS =====
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Authorization, Content-Type, Accept, Origin" always;
        add_header Access-Control-Allow-Credentials "true" always;

        ## Préflight CORS
        if ($request_method = OPTIONS) {
            return 204;
        }

        location ~ ^/(webhook|webhook-test|webhook-waiting|api|form|rest|mcp)(/.*)?$ {
            proxy_pass http://localhost:5678/$1$2$is_args$args;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;

            proxy_http_version 1.1;
            proxy_cache off;
            proxy_buffering off;
        }

        location /mcp/ {
            proxy_http_version 1.1;
            gzip off;
            chunked_transfer_encoding off;
            proxy_set_header Connection '';
        }

        location / {
            return 404;
        }
    }
}
