name: Drawnix2
version: "26.3.2"
slug: drawnix2
description: Open source whiteboard tool (SaaS) with integrated whiteboard, including mind maps, flowcharts, and free drawing
url: https://github.com/LeGitHubDeTai/ha_addons/tree/main/drawnix
panel_icon: "mdi:draw"
startup: services
boot: auto

ingress: true
ingress_port: 7200

panel_icon: mdi:draw
panel_title: Drawnix

ports:
  7200/tcp: 7200

image: pubuzhixing/drawnix:v0.3.0

arch:
  - amd64
  - aarch64
  - armv7