[supervisord]
user=root
nodaemon=true
loglevel=info
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=10MB
logfile_backups=2

[program:gitea]
command=/usr/local/bin/gitea web
autorestart=unexpected
stdout_logfile=/var/log/supervisor/gitea.log
stderr_logfile=/var/log/supervisor/gitea-error.log
user=git
environment=USER=git,HOME=/data/git,GITEA_WORK_DIR=/data/gitea

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx-error.log
user=root
