build_from:
  amd64: lscr.io/linuxserver/nzbget:amd64-v26.3-ls265
  aarch64: lscr.io/linuxserver/nzbget:arm64v8-v26.3-ls265
labels:
  org.opencontainers.image.title: "NZBGet"
  org.opencontainers.image.description: "Client de téléchargement Usenet (NZBGet) pour Home Assistant"
  org.opencontainers.image.source: "https://github.com/LeGitHubDeTai/ha_addons/tree/main/nzbget"
  org.opencontainers.image.licenses: "GPL-2.0-or-later"
