build_from:
  amd64: "lscr.io/linuxserver/lidarr:amd64-nightly-3.1.6.5078-ls218"
  aarch64: "lscr.io/linuxserver/lidarr:arm64v8-nightly-3.1.6.5078-ls218"
labels:
  org.opencontainers.image.title: "Lidarr Nightly"
  org.opencontainers.image.description: "Gestionnaire de collection musicale (Lidarr, branche nightly) pour Home Assistant"
  org.opencontainers.image.source: "https://github.com/LeGitHubDeTai/ha_addons/tree/main/lidarr_nightly"
  org.opencontainers.image.licenses: "GPL-3.0-only"
