build_from:
  amd64: "lscr.io/linuxserver/obsidian:amd64-v1.9.14-ls94"
  aarch64: "lscr.io/linuxserver/obsidian:arm64v8-v1.9.14-ls94"
labels:
  org.opencontainers.image.title: "Home Assistant & Obsidian"
  org.opencontainers.image.description: "Obsidian Notes Server pour Home Assistant"
  org.opencontainers.image.source: "https://github.com/LeGitHubDeTai/ha_addons/obsidian"
  org.opencontainers.image.licenses: "MIT license"